---
# %BEGIN_COPYRIGHT%
# 
# Copyright 2015-2020 Ian McWilliam (kaosagnt@gmail.com).
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# %END_COPYRIGHT%

# Disable an existing user login on remote node. Set the expires on
# u*ix Operating systems that support it to disable all forms of login.
- hosts: "{{ hosts | default('localhost') }}"
  name: "Disable an existing user login on remote node."
  become: yes

  vars_prompt:
    - name: "username"
      prompt: "Enter a username"
      private: no

#  vars:
#       print_information: true

  tasks:
    - include: ../common/common_information.yml

#    - name: Debug
#      local_action: command printf " {{ username.find(':') }} "
#      changed_when: false

    - name: Invalid User name
      local_action: command printf "Invalid username."
      when: username.find(':') >= 0
            or
            username.find(' ') >= 0
            or
            username|length >= 32
            or
            username == ""
      failed_when: true
      changed_when: false

    # expires takes the ansible epoch and takes roughly a year away
    # from this figure so it is in the past.
    - name: Disable user login on remote node
      user:
           name: "{{ username }}"
           expires: "{{ (ansible_date_time.epoch|int - 31556926|int) }}"
      register: disable_user

    #- name: Debug disable_user
    #  local_action: command printf "{{ disable_user }}\n\n{{ ansible_date_time.epoch }}\n"
    #  changed_when: false
