---
# %BEGIN_COPYRIGHT%
# 
# Copyright 2015-2019 Ian McWilliam (kaosagnt@gmail.com).
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# %END_COPYRIGHT%

# Execute yum/dnf repolist on RHEL/CENTOS hosts
- hosts: "{{ hosts | default('localhost') }}"
  name: "Execute yum/dnf repolist on RHEL/CENTOS hosts"
  become: yes

  vars_prompt:
    - name: "repo_type"
      prompt: "\nEnter the lookup type. (e) - enabled, (d) disabled RPM repositories\nor leave blank for all"
      private: no


#  vars:
#       print_information: true

  tasks:
    - include: ../../common/common_information.yml

    - name: "Valid repo list type?"
      local_action: command printf "Invalid RPM repository list type."
      when: repo_type not in ('', 'e', 'd')
      failed_when: true

    - name: "Is repo list type all?"
      set_fact:
               repo_type: "all"
      when: repo_type == ""
      changed_when: false

    - name: "Is repo list type enabled?"
      set_fact:
               repo_type: "enabled"
      when: repo_type == "e"
      changed_when: false

    - name: "Is repo list type disabled?"
      set_fact:
               repo_type: "disabled"
      when: repo_type == "d"
      changed_when: false

    - name: "Include Yum repolist"
      include: yum-repolist.yml
      when: (ansible_os_family == 'RedHat')
            and
            (ansible_lsb.major_release|int >= 5 and
             ansible_lsb.major_release|int <= 7)
      changed_when: false

    - name: "Include DNF repolist"
      include: dnf-repolist.yml
      when: ((ansible_os_family == 'RedHat')
            and
            (ansible_lsb.major_release|int >= 8))
      changed_when: false
