---
# %BEGIN_COPYRIGHT%
# 
# Copyright 2015-2017 Ian McWilliam (kaosagnt@gmail.com).
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# %END_COPYRIGHT%

# Update RPM package to the latest release. 
# on RHEL/CENTOS hosts <= 7

    - name: Yum update RPM
      yum:
          pkg: "{{ item }}"
          disablerepo: "{{ disable_repo }}"
          enablerepo: "{{ enable_repo }}"
          state: latest
      when: (ansible_os_family == 'RedHat') 
            and
            (ansible_lsb.major_release|int >= 5 and
             ansible_lsb.major_release|int <= 7)
      register: yum_rpm_update
      with_items:
        - "{{ rpm_package.split(',') }}"

    - name: Assign variables v1
      set_fact:
               print_yum_update: "{{ yum_rpm_update }}"
      when: ansible_version.major|int == 1
      changed_when: false

    - name: Assign variables v2
      set_fact:
               print_yum_update: "{{ yum_rpm_update.results[0] }}"
      when: ansible_version.major|int == 2
      changed_when: false

    - include: ../common/common_yum_tasks.yml

#    - name: debug
#      local_action: command printf "{{ print_yum_update.results }}\n\n"
#      local_action: command printf "\n\n{{ yum_rpm_update['results'] }}\n\n"
#      changed_when: false
