---
# %BEGIN_COPYRIGHT%
#
# Copyright 2015-2026 Ian McWilliam (kaosagnt@gmail.com).
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# %END_COPYRIGHT%

# Open a network port in firewalld.
- hosts: "{{ hosts | default('localhost') }}"
  name: "Open a network port in firewalld"
  become: true

  vars:
    source_ip_s: ""
    protocol_s: "tcp"
    rich_rule: ""
    ip_ver: "ipv4"
#    print_information: true

  vars_prompt:
    - name: "port_numbers"
      prompt: "Enter the port number(s)\n(seperated by a comma for multiple ports)"
      private: false

    - name: "protocol"
      prompt: "\nEnter the TCP/IP protocol for the port(s) (leave blank for default 'tcp')"
      private: false

    - name: "source_ip"
      prompt: "\nEnter the source IP / network to restrict port access (leave blank for all network access)"
      private: false

    - name: "zone_s"
      prompt: "\nEnter the zone to apply the rule to (leave blank for default 'public')"
      private: false

  tasks:
    - import_tasks: ../../common/common_information.yml

    - import_tasks: network-common-checks.yml

    # Open a network port in firewalld.

    - name: "Insert firewalld rule for port(s) provided - ALL IP addresses"
      firewalld:
        port: "{{ item }}/{{ protocol_s }}"
        permanent: true
        state: enabled
        immediate: true
        zone: "{{ zone_s }}"
      when: (
             (ansible_os_family == 'RedHat'
              and
              ansible_lsb.major_release|int >= 7
             )
             or
             (
              hostvars[inventory_hostname]['use_iptables'] is defined
              and
              not hostvars[inventory_hostname]['use_iptables'] | bool
             )
            )
            and
            (source_ip_s | length == 0)
      register: add_port_firewalld
      with_items:
        - "{{ port_numbers.split(',') }}"

    - name: "Insert firewalld rule for port(s) provided - Restrict IP addresses"
      firewalld:
        rich_rule: 'rule family="{{ ip_ver }}" source address="{{ source_ip_s }}" port port="{{ item }}" protocol="{{ protocol_s }}" accept'
        permanent: true
        state: enabled
        immediate: true
        zone: "{{ zone_s }}"
      when: (
             (ansible_os_family == 'RedHat'
              and
              ansible_lsb.major_release|int >= 7
             )
             or
             (
              hostvars[inventory_hostname]['use_iptables'] is defined
              and
              not hostvars[inventory_hostname]['use_iptables'] | bool
             )
            )
            and
            (source_ip_s | length > 0)
      register: add_port_firewalld
      with_items:
        - "{{ port_numbers.split(',') }}"
